### ISSUE TITLE
Risco enorme!!

### ISSUE THREAD

**Issue by RochaCarla** [fga-eps-mds/2019.2-FoodCare-WebApp#5]
Pessoal,
1 commit a 2 semanas da R1 é inaceitável! 

Corram atrás do prejuizo :P

**Comment by roginaldosemog** [comment]
O repositório na qual a issue foi aberta é referente ao front-end do produto.
Sabemos que o repositório não está devidamente documentado, a issue que resolverá a documentação é a [issue #39 repositório da API](https://github.com/fga-eps-mds/2019.2-FoodCare/issues/39).
